### ISSUE TITLE
mixin下还有没有提交的文件吧

### ISSUE THREAD

**Issue by dev-cheng** [glore/library#1]
cart和demo没有提交，run dev的时候报这个错
[Error] 找不到文件: D:\project\wxapp\library\src\mixins\demo
[Error] 找不到文件: D:\project\wxapp\library\src\mixins\demo
[Error] 找不到文件: D:\project\wxapp\library\src\mixins\cart
[Error] 找不到文件: D:\project\wxapp\library\src\mixins\cart
[Error] 找不到文件: D:\project\wxapp\library\src\mixins\demo
[Error] 找不到文件: D:\project\wxapp\library\src\mixins\demo

**Comment by glore** [comment]
多余的文件，已经从代码文件里删除了。
