### ISSUE TITLE
执行 npm run dev 出现下列几个错误，如何解决？

### ISSUE THREAD

**Issue by zhjq19660117** [glore/library#4]
1、app.wpy 28 error:
4:8 error 'http' is defined but never used no-unused-vars
...
![complied-error-app](https://user-images.githubusercontent.com/726117/41707940-e021267a-7571-11e8-8a2c-93ed883eddb5.PNG)

2、unpage.wpy
...
![complied-error-unpage](https://user-images.githubusercontent.com/726117/41708149-5aaf7c70-7572-11e8-9dac-8500298e1023.PNG)

谢谢

**Comment by JusticeShi** [comment]
同样遇到这个问题，楼主有解决吗

**Comment by Byantdzf** [comment]
再拉一下代码，已解决！个人习惯使用ESLint语法检测，开发者可从wepy.config.js文件里将13行的eslint改为false即可
